configfile: "/mnt/cbis/home/yongshan/majiq_snakemake/config/config.yaml"
include: "rules/common.smk"
include: "rules/majiq_build.smk"
include: "rules/majiq_delta_psi.smk"

rule all:
    input:
        expand(config["BASE_PATH"]+"/results/majiq_build/{experiment}/majiq.log",experiment=EXPERIMENTS),
        expand(config["BASE_PATH"]+"/results/majiq_delta_psi/{experiment}/ctr-cko.deltapsi.tsv",experiment=EXPERIMENTS)