configfile: "../../../config/config.yaml"
include: "../../../common_rules/utils.smk"
include: "../../../common_rules/ref.smk"
include: "rules/ensembl.smk"
include: "rules/STAR_align.smk"

rule all:
	input:
		gtf_file_path(filtered=False,gz=False),gtf_file_path(filtered=True,gz=False), genome_file_path(gz=False,dna=True), genome_file_path(gz=False,dna=False), STAR_output()