configfile: "/mnt/cbis/home/yongshan/SpliCeAT/de_analysis/config/config.yaml"

include: "rules/common.smk"
include: "rules/kallisto_quant.smk"

rule all:
    input:
        expand(config["BASE_PATH"]+"/de_analysis/results/kallisto_quant_out/{sample_name}/abundance.tsv",sample_name=SAMPLES)
