configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/kallisto_quant.smk"
include: "rules/sleuth.smk"

rule all:
    input:
        expand(config["BASE_PATH"]+"/de_analysis/results/kallisto_quant_out/{sample_name}/abundance.tsv",sample_name=SAMPLES),
        config["BASE_PATH"]+"/de_analysis/results/sleuth/collapsed_differential_transcript_analysis_tpm.csv",
        config["BASE_PATH"]+"/de_analysis/results/sleuth/collapsed_differential_transcript_analysis.csv",
        config["BASE_PATH"]+"/de_analysis/results/sleuth/uncollapsed_differential_transcript_analysis_tpm.csv",
        config["BASE_PATH"]+"/de_analysis/results/sleuth/uncollapsed_differential_transcript_analysis.csv"
