configfile: "../../../config/config.yaml"
include: "../../../common_rules/ref.smk"
include: "../../../common_rules/move_results.smk"
include: "../../../common_rules/utils.smk"
include: "rules/kallisto_quant.smk"
include: "rules/sleuth.smk"

rule all:
    input:
        expand("results/kallisto_quant_out/{sample_name}/abundance.tsv",sample_name=SAMPLES),
        "results/sleuth/collapsed_differential_transcript_analysis_tpm.csv",
        "results/sleuth/collapsed_differential_transcript_analysis.csv",
        "results/sleuth/uncollapsed_differential_transcript_analysis_tpm.csv",
        "results/sleuth/uncollapsed_differential_transcript_analysis.csv"