name: config

pipeline_dir: "/mnt/gtklab01/megha/SpliCeAT_new/" #path to SpliCeAT directory

ref:
  species: "Mus_musculus"
  build: "GRCm39"
  ensembl_release: 115
  flavor: "chr" #check ensembl for other options

samples: "design.tsv"

experiment:
  name: "spliceat_replication"
  biotype: "protein_coding"
  max_transcript_support_level: 3
  strandedness: "reverse"
  readlen: 150
  groups: [ "control", "treated" ]

bgzip:
  threads: 4

leafcutter:
  activate: True
  max_intron_length: 500000
  min_samples_per_group: 2
  cluster_support_min: 50

majiq:
  activate: True
  license: "/mnt/gtklab01/megha/SpliCeAT_add/majiq_license_academic_official.lic"
  build_extra: ""

whippet:
  activate: True
  bam_groups:
  - "treated"
  bam_min_reads: 20

stringtie:
  activate: True
  threads: 4
  strand: rf
  min_juncs: 20

kallisto:
  bootstraps: 100
  threads: 4