configfile: "config/config.yaml"
include: "rules/common.smk"
include: "rules/ref.smk"

include: "rules/leafcutter.smk"
include: "rules/majiq.smk"
include: "rules/whippet.smk"

container: "docker://condaforge/miniforge3:latest"

rule all:
    input:
        [ f for f in [
            f"results/{genome_release_name()}_filtered.gff3.gz",
            majiq_output(),
            leafcutter_output(),
            whippet_output(),
        ] if f is not None ]
