confs: /mnt/cbis/home/yongshan/majiq_snakemake/config/confs.tsv
delta_psi_samples: /mnt/cbis/home/yongshan/majiq_snakemake/config/delta_psi_samples.tsv
BASE_PATH: /mnt/cbis/home/yongshan/majiq_snakemake
gtf: /mnt/cbis/home/yongshan/majiq_snakemake/input/gencode.vM29.primary_assembly.annotation.gff3
build_out: /mnt/cbis/home/yongshan/majiq_snakemake/results/majiq_build/{experiment}
delta_out: /mnt/cbis/home/yongshan/majiq_snakemake/results/majiq_delta_psi/{experiment}
experiment_sample_names: /mnt/cbis/home/yongshan/majiq_snakemake/config/experiment_sample_names.tsv
